# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sendsms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='Phone_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone_Number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
